# Generated by Django 4.1.13 on 2024-12-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('energia_kcal', models.FloatField(blank=True, null=True)),
                ('energia_kj', models.FloatField(blank=True, null=True)),
                ('agua_g', models.FloatField(blank=True, null=True)),
                ('proteinas_totales_g', models.FloatField(blank=True, null=True)),
                ('proteinas_vegetales_g', models.FloatField(blank=True, null=True)),
                ('proteinas_animal', models.FloatField(blank=True, null=True)),
                ('grasa_total_g', models.FloatField(blank=True, null=True)),
                ('carbohidratos_disponibles_g', models.FloatField(blank=True, null=True)),
                ('fibra_dietaria_g', models.FloatField(blank=True, null=True)),
                ('cenizas_g', models.FloatField(blank=True, null=True)),
                ('calcio_mg', models.FloatField(blank=True, null=True)),
                ('fosforo_mg', models.FloatField(blank=True, null=True)),
                ('zinc_mg', models.FloatField(blank=True, null=True)),
                ('hierro_mg', models.FloatField(blank=True, null=True)),
                ('caroteno_equivalentes_totales_ug', models.FloatField(blank=True, null=True)),
                ('vitaminaA_equivalentes_totales_ug', models.FloatField(blank=True, null=True)),
                ('tiamina_mg', models.FloatField(blank=True, null=True)),
                ('riboflavina_mg', models.FloatField(blank=True, null=True)),
                ('niacina_mg', models.FloatField(blank=True, null=True)),
                ('vitaminaC_mg', models.FloatField(blank=True, null=True)),
                ('acido_folico_ug', models.FloatField(blank=True, null=True)),
                ('sodio_mg', models.FloatField(blank=True, null=True)),
                ('potasio_mg', models.FloatField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.grupo')),
            ],
            options={
                'verbose_name_plural': 'Alimentos',
            },
        ),
    ]
