# Generated by Django 4.2.17 on 2025-01-04 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('energia_kcal', models.FloatField(blank=True, null=True, verbose_name='Energía(kcal)')),
                ('energia_kj', models.FloatField(blank=True, null=True, verbose_name='Energía(kj)')),
                ('agua_g', models.FloatField(blank=True, null=True, verbose_name='Agua(g)')),
                ('proteinas_totales_g', models.FloatField(blank=True, null=True, verbose_name='Proteínas totales(g)')),
                ('proteinas_vegetales_g', models.FloatField(blank=True, null=True, verbose_name='Proteínas vegetales(g)')),
                ('proteinas_animal', models.FloatField(blank=True, null=True, verbose_name='Proteínas animal')),
                ('grasa_total_g', models.FloatField(blank=True, null=True, verbose_name='Grasa total(g)')),
                ('carbohidratos_disponibles_g', models.FloatField(blank=True, null=True, verbose_name='Carbohidratos disponibles(g)')),
                ('fibra_dietaria_g', models.FloatField(blank=True, null=True, verbose_name='Fibra dietaria(g)')),
                ('cenizas_g', models.FloatField(blank=True, null=True, verbose_name='Cenizas(g)')),
                ('calcio_mg', models.FloatField(blank=True, null=True, verbose_name='Calcio(mg)')),
                ('fosforo_mg', models.FloatField(blank=True, null=True, verbose_name='Fósforo(mg)')),
                ('zinc_mg', models.FloatField(blank=True, null=True, verbose_name='Zinc(mg)')),
                ('hierro_mg', models.FloatField(blank=True, null=True, verbose_name='Hierro(mg)')),
                ('caroteno_equivalentes_totales_ug', models.FloatField(blank=True, null=True, verbose_name='Caroteno equivalentes totales(ug)')),
                ('vitaminaA_equivalentes_totales_ug', models.FloatField(blank=True, null=True, verbose_name='Vitamina A equivalentes totales(ug)')),
                ('tiamina_mg', models.FloatField(blank=True, null=True, verbose_name='Tiamina(mg)')),
                ('riboflavina_mg', models.FloatField(blank=True, null=True, verbose_name='Riboflavina(mg)')),
                ('niacina_mg', models.FloatField(blank=True, null=True, verbose_name='Niacina(mg)')),
                ('vitaminaC_mg', models.FloatField(blank=True, null=True, verbose_name='Vitamina C(mg)')),
                ('acido_folico_ug', models.FloatField(blank=True, null=True, verbose_name='Ácido fólico(ug)')),
                ('sodio_mg', models.FloatField(blank=True, null=True, verbose_name='Sodio(mg)')),
                ('potasio_mg', models.FloatField(blank=True, null=True, verbose_name='Potasio(mg)')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.grupo')),
            ],
            options={
                'verbose_name_plural': 'Alimentos',
            },
        ),
    ]
