# Generated by Django 4.2.17 on 2024-12-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
