# Generated by Django 4.2.17 on 2025-02-01 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDietetico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('nombre_plan', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nombre del Plan')),
                ('objetivo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Objetivo')),
                ('formula', models.CharField(choices=[('OMS', 'OMS'), ('Harris Benedict', 'Harris Benedict')], max_length=30, verbose_name='Fórmula a Utilizar')),
                ('calorias_requeridas', models.IntegerField(verbose_name='Calorías Requeridas')),
                ('calorias_a_planificar', models.IntegerField(verbose_name='Calorías a Planificar')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Término')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('porcentaje_proteina', models.FloatField(verbose_name='Proteína (%)')),
                ('porcentaje_carbohidrato', models.FloatField(verbose_name='Carbohidratos (%)')),
                ('porcentaje_grasa', models.FloatField(verbose_name='Grasa (%)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'Planes Dietéticos',
            },
        ),
    ]
